const up = Math.sqrt(2);
const price = (19.99).toPrecision(4);
const swapped = "banana".replace("an", "AN");
const ch = "hello".at(0);
const n = Number.parseFloat("3.14");
void up;
void price;
void swapped;
void ch;
void n;
